### ISSUE TITLE
 python-joblib fails to build with Python 3.9: AttributeError: '_SafeQueue' object has no attribute '_notempty'

### ISSUE THREAD

**Issue by thibaultlanglois** [joblib/joblib#1140]
This problem is mentioned [here](https://bugzilla.redhat.com/show_bug.cgi?id=1831128) and [here](https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1769410.html). 
I did not find a reference here. 
Has it been fixed ? Is there a workaround ?

**Comment by lesteve** [comment]
This should be fixed since joblib 0.17.0, closing. Feel free to reopen if that is not the case.

As hinted in the Debian email in your post, the root problem was fixed in loky 2.9.0 in https://github.com/joblib/loky/pull/250.
