### ISSUE TITLE
Old joblib archives not readable whe upgrading pandas to 0.20.1

### ISSUE THREAD

**Issue by matjazk** [joblib/joblib#529]
Going from pandas 0.18.1 to 0.20.1 I encountered the following problems when loading old archives, created with `joblib`. `joblib.load` fails with an error:
`ImportError: No module named 'pandas.indexes'`

When I fixed this (see the first workaround), there was an error
`AttributeError: module 'pandas.core.base' has no attribute 'FrozenNDArray'`

After the second workaround, archives load. 

Apparently, this is pandas issue, as it happens also when pickling (before) and unpickling (after updating to 0.20.1) pandas dataframes. In this case devs suggest using `pandas.read_pickle` and not `pickle.load`, as "pandas.read_pickle is the pickle reader and makes things backward compatible".  Can anything be done on joblib side to ensure long-term readability of archives?

```
import sys
# 1
import pandas.core.indexes 
sys.modules['pandas.indexes'] = pandas.core.indexes
# 2
import pandas.core.base, pandas.core.indexes.frozen
setattr(sys.modules['pandas.core.base'],'FrozenNDArray', pandas.core.indexes.frozen.FrozenNDArray)
```

**Comment by GaelVaroquaux** [comment]
> Can anything be done on joblib side to ensure long-term readability of
> archives?

The goal of joblib is to be blackbox and support everything. As a
consequence it will always be less optimal as a library-specific code. I
think that the suggestion of the pandas developers is the good one.
