### ISSUE TITLE
1.3.0 ContextLib Error: ImportError: cannot import name 'nullcontext'

### ISSUE THREAD

**Issue by Leniox** [joblib/joblib#1474]
I believe 1.3.0 is depending on Python 3.7 specific functionality, [such as contextlib import nullcontext](https://github.com/joblib/joblib/compare/1.2.0...1.3.0#diff-e4dff8042ce45b443faf49605b75a58df35b8c195978d4a57f4afa695b406bdcR23)

contextlib is [introduced in Python 3.7](https://docs.python.org/3/library/contextlib.html#contextlib.nullcontext)

However, the [latest conda feedstock for 1.3.0  ](https://github.com/conda-forge/joblib-feedstock/blob/ef929f3216f930b494e80f357ff8f5d92ccbe9fa/recipe/meta.yaml) still relies on python >= 3.6.

Thus, if you use Python 3.6, certain functionalities will fail.

**Comment by Leniox** [comment]
https://github.com/conda-forge/joblib-feedstock/pull/38

**Comment by ogrisel** [comment]
We don't support Python 3.6 in joblib 1.3.0 anymore:

https://github.com/joblib/joblib/blob/1.3.0/pyproject.toml#L28C16-L28C26

So we indeed need to align the feedstock metadata accordingly to be consistent.

Thanks for the report.

**Comment by fcharras** [comment]
To avoid the dependency tree resolution to joblib 1.3.0 for python 3.6 we would also need to yank the joblib 1.3.0 release on conda

**Comment by maartenbreddels** [comment]
That would be great, hitting that issue in CI now for vaex.

**Comment by fcharras** [comment]
Was this issue solved after https://github.com/conda-forge/joblib-feedstock/pull/38 ?

**Comment by blueivy1117** [comment]
Hi, has this issue been resolved yet? I cannot run DetermineGermlineContigPloidy in my conda environment, returned error with "ImportError: cannot import name 'nullcontext'"

**Comment by tomMoral** [comment]
Yes, the failing release should  have been yanked in https://github.com/conda-forge/admin-requests/pull/764
